# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

JupyterPort: 8888

image:
  pullPolicy: IfNotPresent
  clusterRepository: {{ NAUTA.ExperimentImage }}

service:
  type: ClusterIP

resources:
  requests:
    cpu: 19
    memory: 93604421089
  limits:
    cpu: 19
    memory: 93604421089

cpu: null
memory: null

experimentName:  {{ NAUTA.ExperimentName }} 
podCount: 1

cpu_fraction: 0.5
memory_fraction: 0.5
